### ISSUE TITLE
Build or Generate

### ISSUE THREAD

**Issue by gngchrs** [nairobi-gophers/nairobi-gophers.github.io#1]
Between building it or using a static site generator, which one seems preferable?

**Comment by jumaallan** [comment]
Generating is more preferable. I only setup a template for this. Since you are good at this, I would suggest you help set up the site for us 🚀

**Comment by gngchrs** [comment]
Yeah, there a couple, but I don't fare very well in user-facing. 

The more inclusive discussion would be around what the site entails. We would benefit from looking at examples.

> Generating is more preferable. I only setup a template for this. Since you are good at this, I would suggest you help set up the site for us 🚀

**Comment by jumaallan** [comment]
My thoughts were, an informative site, about us and the group, and then later have sections to share meetup photos, talks, events etc

> Yeah, there a couple, but I don't fare very well in user-facing.
> 
> The more inclusive discussion would be around what the site entails. We would benefit from looking at examples.
> 
> > Generating is more preferable. I only setup a template for this. Since you are good at this, I would suggest you help set up the site for us 🚀

**Comment by RawPlutonium** [comment]
Can everyone contribute? And if so what's the procedure

**Comment by gngchrs** [comment]
closed due to inactivity
